/* Generated By:JavaCC: Do not edit this line. SimpleDBMSParser.java */
//importimport com.sleepycat.je.Database;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.DatabaseConfig;
import com.sleepycat.je.DatabaseEntry;
import com.sleepycat.je.Cursor;
import com.sleepycat.je.Environment;
import com.sleepycat.je.EnvironmentConfig;
import com.sleepycat.je.LockMode;
import com.sleepycat.je.OperationStatus;

import java.io.File;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.Iterator;
import custom.*;
import java.lang.Math;

import com.sleepycat.bind.EntryBinding;
import com.sleepycat.bind.serial.StoredClassCatalog;
import com.sleepycat.bind.serial.SerialBinding;

public class SimpleDBMSParser implements SimpleDBMSParserConstants {
  /*Query Return values */
  public static final int PRINT_CREATE_TABLE = 1;
  public static final int PRINT_DROP_TABLE = 2;
  public static final int PRINT_DESC = 3;
  public static final int PRINT_SHOW_TABLES = 4;
  public static final int PRINT_SELECT = 5;
  public static final int PRINT_INSERT = 6;
  public static final int PRINT_DELETE = 7;

  public static DatabaseHandler DBH = new DatabaseHandler();
  public static DatabaseManage DM = new DatabaseManage(DBH);
  public static DatabaseDefine DD = new DatabaseDefine(DBH);
  public static void main(String args[]) throws ParseException
  {

    SimpleDBMSParser parser = new SimpleDBMSParser(System.in);
    System.out.print("DB_2014-10469> ");

    while (true)
    {
      try
      {
        parser.command();

      }
      catch (Exception e)
      {
        errorMsg.printMessage(errorMsg.PRINT_SYNTAX_ERROR, "", true);
        //System.out.println(e.getMessage()); // for Debug, if you remove comment symbol, you can see what token is not matched when error comes.        SimpleDBMSParser.ReInit(System.in);
      }
    }
  }

//parse the whole SQL command  static final public void command() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CREATE_TABLE:
    case DROP_TABLE:
    case DESC:
    case SHOW_TABLES:
    case SELECT:
    case INSERT_INTO:
    case DELETE_FROM:
      queryList();
      break;
    case EXIT:
      jj_consume_token(EXIT);
      jj_consume_token(SEMICOLON);
       DBH.close();
       System.exit(0);
      break;
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

//parse querylist = > query;query;query;...//after parse each query, it print message according to query comment number  static final public void queryList() throws ParseException {
  int q;
  queryConfig qC = new queryConfig();
    label_1:
    while (true) {
      q = query(qC);
      jj_consume_token(SEMICOLON);
          switch(q)
          {
            case PRINT_CREATE_TABLE:
                //check if primary definition is more than 1 
                if(qC.primary_def_count > 1)
                {
                        errorMsg.printMessage(errorMsg.DUPLICATE_PRIMARYKEY_DEF_ERROR, "", true);
                        {if (true) return;}
                }
                DD.createTable(qC.table);
                break;
                case PRINT_DROP_TABLE:
                        DD.dropTable(qC.table_name);
                        break;
                case PRINT_DESC:
                        DD.desc(qC.table_name);
                        break;
                case PRINT_SHOW_TABLES:
                        DD.showTables();
                        break;
                case PRINT_SELECT:
                        DM.select(qC.select_name_list, qC.select_table_name_list, qC.where_expression);
                        break;
                case PRINT_INSERT:
                        DM.insert(qC.table_name, qC.record, qC.record_match_attributes);
                        break;
                case PRINT_DELETE:
                        DM.delete(qC.table_name, qC.where_expression);
                        break;
       }
       //error handling here **************************************************
       qC = new queryConfig();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CREATE_TABLE:
      case DROP_TABLE:
      case DESC:
      case SHOW_TABLES:
      case SELECT:
      case INSERT_INTO:
      case DELETE_FROM:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
    }
  }

// parse query  static final public int query(queryConfig qC) throws ParseException {
  int q;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CREATE_TABLE:
      qC.primary_def_count = createTableQuery(qC.table);
      q = PRINT_CREATE_TABLE;
      break;
    case DROP_TABLE:
      qC.table_name = dropTableQuery();
          q = PRINT_DROP_TABLE;
      break;
    case DESC:
      qC.table_name = descQuery();
          q = PRINT_DESC;
      break;
    case SHOW_TABLES:
      showTablesQuery();
          q = PRINT_SHOW_TABLES;
      break;
    case SELECT:
      selectQuery(qC);
          q = PRINT_SELECT;
      break;
    case INSERT_INTO:
      insertQuery(qC);
          q = PRINT_INSERT;
      break;
    case DELETE_FROM:
      deleteQuery(qC);
          q = PRINT_DELETE;
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return q;}
    throw new Error("Missing return statement in function");
  }

  static final public void deleteQuery(queryConfig qC) throws ParseException {
    jj_consume_token(DELETE_FROM);
    qC.table_name = tableName();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case WHERE:
      whereClause(qC.where_expression);
      break;
    default:
      jj_la1[3] = jj_gen;
      ;
    }
  }

  static final public void insertQuery(queryConfig qC) throws ParseException {
    jj_consume_token(INSERT_INTO);
    qC.table_name = tableName();
    insertColumnsAndSource(qC);
  }

  static final public void insertColumnsAndSource(queryConfig qC) throws ParseException {
        ArrayList<String> RMA = new ArrayList<String>();
        ArrayList<Types> values;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LEFT_PAREN:
      RMA = columnNameList();
      break;
    default:
      jj_la1[4] = jj_gen;
      ;
    }
    values = valueList();
    qC.record_match_attributes = RMA;
    qC.record = values;
  }

  static final public ArrayList<Types> valueList() throws ParseException {
        ArrayList<Types> VL = new ArrayList<Types>();
    jj_consume_token(VALUES);
    jj_consume_token(LEFT_PAREN);
    value(VL);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[5] = jj_gen;
        break label_2;
      }
      jj_consume_token(COMMA);
      value(VL);
    }
    jj_consume_token(RIGHT_PAREN);
        {if (true) return VL;}
    throw new Error("Missing return statement in function");
  }

  static final public void value(ArrayList<Types> VL) throws ParseException {
  Types value;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NULL:
      jj_consume_token(NULL);
        VL.add((Types) new NullType());
      break;
    case INT_VALUE:
    case DATE_VALUE:
    case CHAR_STRING:
      value = comparableValue();
                                VL.add(value);
      break;
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void selectQuery(queryConfig qC) throws ParseException {
    jj_consume_token(SELECT);
    selectList(qC.select_name_list);
    tableExpression(qC);
  }

  static final public void tableExpression(queryConfig qC) throws ParseException {
    fromClause(qC.select_table_name_list);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case WHERE:
      whereClause(qC.where_expression);
      break;
    default:
      jj_la1[7] = jj_gen;
      ;
    }
  }

  static final public void whereClause(ExpressionType WE) throws ParseException {
    jj_consume_token(WHERE);
    booleanValueExpression(WE);
  }

  static final public void booleanValueExpression(ExpressionType WE) throws ParseException {
        Token t;
    WE.left_operand = new ExpressionType();
    booleanTerm((ExpressionType) WE.left_operand);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OR:
        ;
        break;
      default:
        jj_la1[8] = jj_gen;
        break label_3;
      }
      t = jj_consume_token(OR);
      WE.right_operand = new ExpressionType();
      WE.operator = t.toString();
      booleanTerm((ExpressionType) WE.right_operand);
    }
  }

  static final public void booleanTerm(ExpressionType WE) throws ParseException {
        Token t;
    WE.left_operand = new ExpressionType();
    booleanFactor((ExpressionType) WE.left_operand);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        ;
        break;
      default:
        jj_la1[9] = jj_gen;
        break label_4;
      }
      t = jj_consume_token(AND);
      WE.right_operand = new ExpressionType();
      WE.operator = t.toString();
      booleanFactor((ExpressionType) WE.right_operand);
    }
  }

  static final public void booleanFactor(ExpressionType WE) throws ParseException {
        ExpressionType temp = WE;
        Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOT:
      t = jj_consume_token(NOT);
      WE.left_operand = (Types) new ExpressionType();
          WE.operator = t.toString();
          temp = (ExpressionType) WE.left_operand;
      break;
    default:
      jj_la1[10] = jj_gen;
      ;
    }
    booleanTest(temp);
  }

  static final public void booleanTest(ExpressionType WE) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT_VALUE:
    case DATE_VALUE:
    case LEGAL_IDENTIFIER:
    case CHAR_STRING:
      predicate(WE);
      break;
    case LEFT_PAREN:
      parenthesizedBooleanExpression(WE);
      break;
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void parenthesizedBooleanExpression(ExpressionType WE) throws ParseException {
    jj_consume_token(LEFT_PAREN);
    booleanValueExpression(WE);
    jj_consume_token(RIGHT_PAREN);
  }

  static final public void predicate(ExpressionType WE) throws ParseException {
    if (jj_2_1(4)) {
      comparisonPredicate(WE);
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LEGAL_IDENTIFIER:
        nullPredicate(WE);
        break;
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public void nullPredicate(ExpressionType WE) throws ParseException {
  SelectName sn = new SelectName();
    if (jj_2_2(2)) {
      // it can solve the conflict tableName()and columnName() 
          sn.tname = tableName();
      jj_consume_token(PERIOD);
    } else {
      ;
    }
    sn.cname = columnName();
    WE.operator = nullOperation();
    WE.left_operand = (Types) new VarType(sn);
  }

  static final public String nullOperation() throws ParseException {
        String temp;
    jj_consume_token(IS);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOT:
      jj_consume_token(NOT);
      jj_consume_token(NULL);
                         temp = "not_null";
      break;
    case NULL:
      jj_consume_token(NULL);
               temp = "null";
      break;
    case NOT_NULL:
      jj_consume_token(NOT_NULL);
                   temp = "not_null";
      break;
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
        {if (true) return temp;}
    throw new Error("Missing return statement in function");
  }

  static final public void comparisonPredicate(ExpressionType WE) throws ParseException {
  Token t;
    WE.left_operand = compOperand();
    t = jj_consume_token(COMP_OP);
    WE.right_operand = compOperand();
        WE.operator = t.toString();
  }

  static final public Types compOperand() throws ParseException {
  Types temp;
  SelectName sn = new SelectName();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT_VALUE:
    case DATE_VALUE:
    case CHAR_STRING:
      temp = comparableValue();
      break;
    case LEGAL_IDENTIFIER:
      if (jj_2_3(2)) {
        // it can solve the conflict tableName()and columnName() 
                        sn.tname = tableName();
        jj_consume_token(PERIOD);
      } else {
        ;
      }
      sn.cname = columnName();
                temp = (Types) new VarType(sn);
      break;
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return temp;}
    throw new Error("Missing return statement in function");
  }

  static final public Types comparableValue() throws ParseException {
  Types temp;
  Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT_VALUE:
      t = jj_consume_token(INT_VALUE);
                          temp = (Types) new IntType(t.toString());
      break;
    case CHAR_STRING:
      t = jj_consume_token(CHAR_STRING);
                            temp = (Types) new CharType(t.toString());
      break;
    case DATE_VALUE:
      t = jj_consume_token(DATE_VALUE);
                           temp = (Types) new DateType(t.toString());
      break;
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
        {if (true) return temp;}
    throw new Error("Missing return statement in function");
  }

  static final public void fromClause(ArrayList<SelectName> STNL) throws ParseException {
    jj_consume_token(FROM);
    tableReferenceList(STNL);
  }

  static final public void tableReferenceList(ArrayList<SelectName> STNL) throws ParseException {
    referedTable(STNL);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[16] = jj_gen;
        break label_5;
      }
      jj_consume_token(COMMA);
      referedTable(STNL);
    }
  }

  static final public void referedTable(ArrayList<SelectName> STNL) throws ParseException {
  SelectName temp = new SelectName();
    temp.tname = tableName();

    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case AS:
      jj_consume_token(AS);
      temp.dname = tableName();
      break;
    default:
      jj_la1[17] = jj_gen;
      ;
    }
    STNL.add(temp);
  }

  static final public void selectList(ArrayList<SelectName> SNL) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STAR:
      jj_consume_token(STAR);
        SNL.add(new SelectName("*", "", ""));
      break;
    case LEGAL_IDENTIFIER:
      selectedColumn(SNL);
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[18] = jj_gen;
          break label_6;
        }
        jj_consume_token(COMMA);
        selectedColumn(SNL);
      }
      break;
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void selectedColumn(ArrayList<SelectName> SNL) throws ParseException {
  SelectName SN = new SelectName();
    if (jj_2_4(2)) {
      // it can solve the conflict tableName()and columnName() 
          SN.tname = tableName();
      jj_consume_token(PERIOD);
    } else {
      ;
    }
    SN.cname = columnName();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case AS:
      jj_consume_token(AS);
      SN.dname = columnName();
      break;
    default:
      jj_la1[20] = jj_gen;
      ;
    }
    SNL.add(SN);
  }

  static final public void showTablesQuery() throws ParseException {
    jj_consume_token(SHOW_TABLES);
  }

  static final public String descQuery() throws ParseException {
  String table_name;
    jj_consume_token(DESC);
    table_name = tableName();
  {if (true) return table_name;}
    throw new Error("Missing return statement in function");
  }

  static final public String dropTableQuery() throws ParseException {
  String table_name;
    jj_consume_token(DROP_TABLE);
    table_name = tableName();
  {if (true) return table_name;}
    throw new Error("Missing return statement in function");
  }

  static final public int createTableQuery(Table table) throws ParseException {
  int pdc = 0;
    jj_consume_token(CREATE_TABLE);
    table.table_name = tableName();
    pdc = tableElementList(table);
            {if (true) return pdc;}
    throw new Error("Missing return statement in function");
  }

  static final public int tableElementList(Table table) throws ParseException {
        int primary_def_count = 0;
        int temp;
    jj_consume_token(LEFT_PAREN);
    temp = tableElement(table);
    primary_def_count += temp;
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[21] = jj_gen;
        break label_7;
      }
      jj_consume_token(COMMA);
      temp = tableElement(table);
      primary_def_count += temp;
    }
    jj_consume_token(RIGHT_PAREN);
    {if (true) return primary_def_count;}
    throw new Error("Missing return statement in function");
  }

  static final public int tableElement(Table table) throws ParseException {
  Attribute attribute = new Attribute();
  int primary_def_count = 0;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LEGAL_IDENTIFIER:
      columnDefinition(attribute);
                table.attributes.add(attribute);
      break;
    case PRIMARY_KEY:
    case FOREIGN_KEY:
      primary_def_count = tableConstraintDefinition(table);
      break;
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return primary_def_count;}
    throw new Error("Missing return statement in function");
  }

  static final public void columnDefinition(Attribute attribute) throws ParseException {
  String temp;
    temp = columnName();
    attribute.set_name(temp);
    dataType(attribute);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOT_NULL:
      jj_consume_token(NOT_NULL);
      attribute.set_is_null(false);
      break;
    default:
      jj_la1[23] = jj_gen;
      ;
    }
  }

  static final public int tableConstraintDefinition(Table table) throws ParseException {
        int primary_def_count = 0;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PRIMARY_KEY:
      primaryKeyConstraint(table);
      primary_def_count = 1;
      break;
    case FOREIGN_KEY:
      referentialConstraint(table);
      break;
    default:
      jj_la1[24] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
        {if (true) return primary_def_count;}
    throw new Error("Missing return statement in function");
  }

  static final public void primaryKeyConstraint(Table table) throws ParseException {
    jj_consume_token(PRIMARY_KEY);
    table.primary_keys = columnNameList();
  }

  static final public void referentialConstraint(Table table) throws ParseException {
        ArrayList<String> referencing;
        ArrayList<String> referenced;
        String reference_table;
        Reference temp = new Reference();
    jj_consume_token(FOREIGN_KEY);
    referencing = columnNameList();
    jj_consume_token(REFERENCES);
    reference_table = tableName();
    referenced = columnNameList();
    temp.refer_chaser_names = referencing;
    temp.refer_target_names = referenced;
    temp.refer_table = reference_table;
    table.referencing.add(temp);
  }

  static final public ArrayList<String> columnNameList() throws ParseException {
        ArrayList<String > list =  new ArrayList();
        String temp;
    jj_consume_token(LEFT_PAREN);
    temp = columnName();
    list.add(temp);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[25] = jj_gen;
        break label_8;
      }
      jj_consume_token(COMMA);
      temp = columnName();
      list.add(temp);
    }
    jj_consume_token(RIGHT_PAREN);
        {if (true) return list;}
    throw new Error("Missing return statement in function");
  }

  static final public void dataType(Attribute attribute) throws ParseException {
  int type = 0;
  Token length_temp;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
      jj_consume_token(INT);
            type = 1;
      break;
    case CHAR:
      jj_consume_token(CHAR);
      jj_consume_token(LEFT_PAREN);
      length_temp = jj_consume_token(INT_VALUE);
      type = 2;
      attribute.set_len(Integer.parseInt(length_temp.toString()));
      jj_consume_token(RIGHT_PAREN);
      break;
    case DATE:
      jj_consume_token(DATE);
             type = 3;
      break;
    default:
      jj_la1[26] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                attribute.set_type(type);
                {if (true) return;}
  }

  static final public String tableName() throws ParseException {
  Token t;
    t = jj_consume_token(LEGAL_IDENTIFIER);
        {if (true) return t.toString();}
    throw new Error("Missing return statement in function");
  }

  static final public String columnName() throws ParseException {
        Token t;
    t = jj_consume_token(LEGAL_IDENTIFIER);
    {if (true) return t.toString();}
    throw new Error("Missing return statement in function");
  }

  static private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_3R_14() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_16()) {
    jj_scanpos = xsp;
    if (jj_3R_17()) {
    jj_scanpos = xsp;
    if (jj_3R_18()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_10() {
    if (jj_scan_token(LEGAL_IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_11() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_12()) {
    jj_scanpos = xsp;
    if (jj_3R_13()) return true;
    }
    return false;
  }

  static private boolean jj_3_2() {
    if (jj_3R_10()) return true;
    if (jj_scan_token(PERIOD)) return true;
    return false;
  }

  static private boolean jj_3_3() {
    if (jj_3R_10()) return true;
    if (jj_scan_token(PERIOD)) return true;
    return false;
  }

  static private boolean jj_3R_15() {
    if (jj_scan_token(LEGAL_IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_13() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_3()) jj_scanpos = xsp;
    if (jj_3R_15()) return true;
    return false;
  }

  static private boolean jj_3R_12() {
    if (jj_3R_14()) return true;
    return false;
  }

  static private boolean jj_3R_18() {
    if (jj_scan_token(DATE_VALUE)) return true;
    return false;
  }

  static private boolean jj_3R_9() {
    if (jj_3R_11()) return true;
    if (jj_scan_token(COMP_OP)) return true;
    if (jj_3R_11()) return true;
    return false;
  }

  static private boolean jj_3_4() {
    if (jj_3R_10()) return true;
    if (jj_scan_token(PERIOD)) return true;
    return false;
  }

  static private boolean jj_3R_17() {
    if (jj_scan_token(CHAR_STRING)) return true;
    return false;
  }

  static private boolean jj_3_1() {
    if (jj_3R_9()) return true;
    return false;
  }

  static private boolean jj_3R_16() {
    if (jj_scan_token(INT_VALUE)) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public SimpleDBMSParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[27];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x140f0220,0x140f0200,0x140f0200,0x400000,0x0,0x0,0x800,0x400000,0x800000,0x1000000,0x400,0x0,0x0,0x1c00,0x0,0x0,0x0,0x100000,0x0,0x20000000,0x100000,0x0,0x6000,0x1000,0x6000,0x0,0x1c0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x8,0x20,0x8480,0x0,0x0,0x0,0x0,0xa488,0x2000,0x0,0xa480,0x8480,0x20,0x0,0x20,0x2000,0x0,0x20,0x2000,0x0,0x0,0x20,0x0,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[4];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public SimpleDBMSParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public SimpleDBMSParser(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new SimpleDBMSParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public SimpleDBMSParser(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new SimpleDBMSParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public SimpleDBMSParser(SimpleDBMSParserTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(SimpleDBMSParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[51];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 27; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 51; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 4; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
