-- MySQL Script generated by MySQL Workbench
-- Wed May 22 19:54:56 2019
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Concert_reservation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Building`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Building` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(200) CHARACTER SET 'utf8' NULL,
  `Location` VARCHAR(200) CHARACTER SET 'utf8' NULL,
  `Capacity` INT UNSIGNED NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Performance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Performance` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(200) CHARACTER SET 'utf8' NULL,
  `Type` VARCHAR(200) CHARACTER SET 'utf8' NULL,
  `Price` INT UNSIGNED NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Audience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Audience` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(200) CHARACTER SET 'utf8' NULL,
  `Gender` VARCHAR(1) CHARACTER SET 'utf8' NULL,
  `Age` INT UNSIGNED NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Assignment` (
  `P_ID` INT UNSIGNED NOT NULL,
  `B_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`P_ID`, `B_ID`),
  INDEX `Building-idx` (`B_ID` ASC),
  CONSTRAINT `Assigment-B`
    FOREIGN KEY (`B_ID`)
    REFERENCES `Building` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `Assignment-P`
    FOREIGN KEY (`P_ID`)
    REFERENCES `Performance` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Book` (
  `A_ID` INT UNSIGNED NULL,
  `P_ID` INT UNSIGNED NOT NULL,
  `B_ID` INT UNSIGNED NOT NULL,
  `Seat` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Seat`, `B_ID`, `P_ID`),
  INDEX `Audience_idx` (`A_ID` ASC),
  INDEX `Building_idx` (`B_ID` ASC),
  INDEX `Performance_idx` (`P_ID` ASC),
  CONSTRAINT `Book-P`
    FOREIGN KEY (`P_ID`)
    REFERENCES `Performance` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `Book-A`
    FOREIGN KEY (`A_ID`)
    REFERENCES `Audience` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `Book-B`
    FOREIGN KEY (`B_ID`)
    REFERENCES `Building` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
